# H2 Database Config
spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  h2:
    console:
      enabled: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 250MB

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO