# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
      - image: circleci/mysql
        environment:
          MYSQL_ROOT_PASSWORD: Root@A123
          MYSQL_DATABASE: sonot
          MYSQL_USER: sonet
          MYSQL_PASSWORD: Root@A123

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/Sonet

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/Sonet

#      Setting Environemt Variables for OAuth2 Google
      - run:
          name: "Google Client ID Environment Variable"
          command: echo 'export spring.security.oauth2.client.registration.google.clientId="405838513888-bfrnubu69sfetunplthroe8b72v7h7kv.apps.googleusercontent.com"'

      - run:
          name: "Google Client Secret Environment Variable"
          command: echo 'export spring.security.oauth2.client.registration.google.clientSecret="G2uZwLOFT7lbXKNjhsym7a7g"'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - sonet-v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - sonet-v1-dependencies-

      # Prevent running tests before going offline, run at the end
      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sonet-v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

      # Test Summary Config
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results
